name: core16
version: 16-2
version-script: |
    # remember to keep version script in sync with "Makefile"
    echo "16-$(date +%Y%m%d)"
summary: core16 runtime environment
description: The core16 runtime environment
confinement: strict
type: base
grade: stable

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - shellcheck
      - gawk
