name: core16
version: 16-2
version-script: |
    # remember to keep version script in sync with "Makefile"
    echo "16-$(date +%Y%m%d)"
summary: core16 runtime environment
description: The core16 runtime environment
confinement: strict
type: base
grade: stable

parts:
  check:
    plugin: dump
    override-pull: |
      if ! apt-cache policy ubuntu-core-config|grep -q ppa.launchpad.net/snappy-dev/image; then
          echo "The ppa:snappy-dev/image PPA is missing."
          echo "This probably means that the build was triggered incorrectly."
          apt-cache policy ubuntu-core-config
          exit 1
      fi

  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - shellcheck
      - gawk
